require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KnownUrlsController do

  # This should return the minimal set of attributes required to create a valid
  # KnownUrl. As you add validations to KnownUrl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KnownUrlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all known_urls as @known_urls" do
      known_url = KnownUrl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:known_urls).should eq([known_url])
    end
  end

  describe "GET show" do
    it "assigns the requested known_url as @known_url" do
      known_url = KnownUrl.create! valid_attributes
      get :show, {:id => known_url.to_param}, valid_session
      assigns(:known_url).should eq(known_url)
    end
  end

  describe "GET new" do
    it "assigns a new known_url as @known_url" do
      get :new, {}, valid_session
      assigns(:known_url).should be_a_new(KnownUrl)
    end
  end

  describe "GET edit" do
    it "assigns the requested known_url as @known_url" do
      known_url = KnownUrl.create! valid_attributes
      get :edit, {:id => known_url.to_param}, valid_session
      assigns(:known_url).should eq(known_url)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KnownUrl" do
        expect {
          post :create, {:known_url => valid_attributes}, valid_session
        }.to change(KnownUrl, :count).by(1)
      end

      it "assigns a newly created known_url as @known_url" do
        post :create, {:known_url => valid_attributes}, valid_session
        assigns(:known_url).should be_a(KnownUrl)
        assigns(:known_url).should be_persisted
      end

      it "redirects to the created known_url" do
        post :create, {:known_url => valid_attributes}, valid_session
        response.should redirect_to(KnownUrl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved known_url as @known_url" do
        # Trigger the behavior that occurs when invalid params are submitted
        KnownUrl.any_instance.stub(:save).and_return(false)
        post :create, {:known_url => { "url" => "invalid value" }}, valid_session
        assigns(:known_url).should be_a_new(KnownUrl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KnownUrl.any_instance.stub(:save).and_return(false)
        post :create, {:known_url => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested known_url" do
        known_url = KnownUrl.create! valid_attributes
        # Assuming there are no other known_urls in the database, this
        # specifies that the KnownUrl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KnownUrl.any_instance.should_receive(:update).with({ "url" => "MyText" })
        put :update, {:id => known_url.to_param, :known_url => { "url" => "MyText" }}, valid_session
      end

      it "assigns the requested known_url as @known_url" do
        known_url = KnownUrl.create! valid_attributes
        put :update, {:id => known_url.to_param, :known_url => valid_attributes}, valid_session
        assigns(:known_url).should eq(known_url)
      end

      it "redirects to the known_url" do
        known_url = KnownUrl.create! valid_attributes
        put :update, {:id => known_url.to_param, :known_url => valid_attributes}, valid_session
        response.should redirect_to(known_url)
      end
    end

    describe "with invalid params" do
      it "assigns the known_url as @known_url" do
        known_url = KnownUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KnownUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => known_url.to_param, :known_url => { "url" => "invalid value" }}, valid_session
        assigns(:known_url).should eq(known_url)
      end

      it "re-renders the 'edit' template" do
        known_url = KnownUrl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KnownUrl.any_instance.stub(:save).and_return(false)
        put :update, {:id => known_url.to_param, :known_url => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested known_url" do
      known_url = KnownUrl.create! valid_attributes
      expect {
        delete :destroy, {:id => known_url.to_param}, valid_session
      }.to change(KnownUrl, :count).by(-1)
    end

    it "redirects to the known_urls list" do
      known_url = KnownUrl.create! valid_attributes
      delete :destroy, {:id => known_url.to_param}, valid_session
      response.should redirect_to(known_urls_url)
    end
  end

end
